"""
Django settings for gtw project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config, Csv
import os
from pathlib import Path
from django.core.validators import EMPTY_VALUES
from django.forms.fields import Field
import pdfkit

# MIDDLEWARE = [
#     "middleware.tailscale_protect.TailscaleProtectMiddleware",  # add first
# ] + MIDDLEWARE


ENV = config("ENV", default="development")
SEF = config("SEF", default="demoefaktura")

Field.default_error_messages['required'] = "Ovo polje je obavezno."

BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

DEBUG = (ENV != "production")

TAILNET_DOMAIN = config("TAILNET_DOMAIN", default="")

if ENV == "production":
    SECRET_KEY = config("SECRET_KEY_PRODUCTION")
    ALLOWED_HOSTS = config("ALLOWED_HOSTS_PRODUCTION", default="localhost", cast=Csv())
    CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", cast=Csv()) #[f"https://{TAILNET_DOMAIN}"]
else:
    SECRET_KEY = config("SECRET_KEY_DEVELOPMENT")
    ALLOWED_HOSTS = config("ALLOWED_HOSTS_DEVELOPMENT", default="localhost", cast=Csv())
    CSRF_TRUSTED_ORIGINS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'gtbook', # my app
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE.insert(0, "middleware.tailscale_protect.TailscaleProtectMiddleware")

ROOT_URLCONF = 'gtw.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gtw.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        "NAME": BASE_DIR / "db" / config("DB_NAME", default="db.sqlite3"),
    }
}

# Redirect unauthenticated users here
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/clients/'

# Redirect after logout
LOGOUT_REDIRECT_URL = '/login/'  # or use name='login' with reverse_lazy

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if ENV == "production":
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # Tailscale terminates TLS
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    USE_X_FORWARDED_HOST = False
    SECURE_PROXY_SSL_HEADER = None

# Session expires after X minutes of inactivity
SESSION_COOKIE_AGE = 1800 # max 1209600 (2 weeks in seconds)
SESSION_SAVE_EVERY_REQUEST = True # Reset the timer on each request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

NBS_USERNAME = config("NBS_USERNAME", default="")
NBS_PASSWORD = config("NBS_PASSWORD", default="")
NBS_LICENCE_ID = config("NBS_LICENCE_ID", default="")

if SEF == "efaktura":
    SEF_API_KEY = config("SEF_API_KEY", default="")
else:
    SEF_API_KEY = config("DEMO_SEF_API_KEY", default="")

#HOOKRELAY_SECRET = config('HOOKRELAY_SECRET')

COMPANY = {
    "VAT_NUMBER": config("VAT_NUMBER", default=""),
    "COMPANY_NAME": config("COMPANY_NAME", default=""),
    "ADDRESS": config("ADDRESS", default=""),
    "CITY": config("CITY", default=""),
    "COMPANY_ID": config("COMPANY_ID", default=""),
    "EMAIL": config("EMAIL", default=""),
    "BANK_ACCOUNT": config("BANK_ACCOUNT", default="")
}

if os.name == "nt":  # Windows
    WKHTML = r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
else:  # Linux / Docker
    WKHTML = "/usr/bin/wkhtmltopdf"

PDFKIT_CONFIG = pdfkit.configuration(wkhtmltopdf=WKHTML)