# Generated by Django 5.0.1 on 2025-08-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='ime',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='adresa',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='defcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='jbkjs',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='kontakt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mbr',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='client',
            name='mesto',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='pib',
            field=models.CharField(default=0, max_length=9),
        ),
        migrations.AddField(
            model_name='client',
            name='postbr',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='client',
            name='tekuci',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
