# Generated by Django 5.0.1 on 2025-09-05 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0002_rename_name_client_ime_remove_client_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad', models.CharField(max_length=100, unique=True)),
                ('post_code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['grad'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='adresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='defcode',
            field=models.IntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='jbkjs',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'JBKJS mora imati tačno 5 cifara.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='mbr',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'MBR mora imati tačno 8 cifara.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='mesto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='pib',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'PIB mora imati tačno 9 cifara.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='postbr',
            field=models.CharField(max_length=5),
        ),
    ]
