# Generated by Django 5.0.1 on 2025-09-05 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0003_mesto_alter_client_adresa_alter_client_defcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtbook.mesto'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postbr',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
