# Generated by Django 5.0.1 on 2025-09-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0004_alter_client_mesto_alter_client_postbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='postbr',
        ),
    ]
