# Generated by Django 5.0.1 on 2025-09-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0005_remove_client_postbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tekuci',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
