# Generated by Django 5.0.1 on 2025-09-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0006_alter_client_tekuci_alter_client_telefon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Klijenti',
        ),
    ]
