# Generated by Django 5.0.1 on 2025-09-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0007_rename_client_klijenti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dok_tip', models.CharField(choices=[('izl_faktura', 'Izlazna faktura'), ('ul_faktura', 'Ulazna faktura'), ('otpremnica', 'Otpremnica'), ('racun', 'Račun')], default='izl_faktura', max_length=25)),
                ('dok_br', models.CharField(max_length=25)),
                ('val_datum', models.DateField(blank=True, null=True)),
                ('br_ponude', models.CharField(blank=True, max_length=25, null=True)),
                ('valuta', models.CharField(default='RSD', max_length=3)),
                ('iznos_P', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('iznos_U', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('status_SEF', models.CharField(default='Nacrt', max_length=25)),
                ('status_fak', models.CharField(default='Neplaćen', max_length=25)),
                ('status_dok', models.BooleanField(default=False)),
                ('requestId', models.CharField(max_length=25)),
                ('salesInvoiceId', models.CharField(max_length=25)),
                ('purchaseInvoiceId', models.CharField(max_length=25)),
                ('documentId', models.CharField(max_length=25)),
                ('napomena', models.TextField(blank=True, null=True)),
                ('klijent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtbook.klijenti')),
            ],
        ),
    ]
