# Generated by Django 5.0.1 on 2025-09-27 16:27

import django.db.models.deletion
import django.db.models.expressions
import gtbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0008_dokumenti'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentStavke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_prometa', models.CharField(choices=[('U', 'usluga'), ('P', 'prodaja')], default='usluga', max_length=7)),
                ('kolicina', models.IntegerField(default=1)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('jed_mere', models.CharField(choices=[('KT', 'komplet'), ('H87', 'kom'), ('HUR', 'h')], max_length=3, verbose_name='Jedinica mere')),
                ('iznos_stavke', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('kolicina'), '*', models.F('cena')), output_field=models.DecimalField(decimal_places=2, max_digits=12))),
            ],
        ),
        migrations.CreateModel(
            name='Transakcije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(choices=[('debit', 'Isplata'), ('credit', 'Uplata')], max_length=10)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tra_vrsta', models.CharField(choices=[('bank', 'Banka'), ('cash', 'Gotovina'), ('other', 'Drugo')], max_length=10)),
                ('napomena', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dokumenti',
            name='faktura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otpremnice', to='gtbook.dokumenti'),
        ),
        migrations.AddField(
            model_name='dokumenti',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', validators=[gtbook.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='dok_br',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='dok_tip',
            field=models.CharField(choices=[('izl_faktura', 'Izlazna faktura'), ('ul_faktura', 'Ulazna faktura'), ('otpremnica', 'Otpremnica'), ('racun', 'Račun')], max_length=25),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='iznos_P',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='iznos_U',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='dokumenti',
            constraint=models.UniqueConstraint(fields=('dok_tip', 'dok_br'), name='idx_dokumenti_unique'),
        ),
        migrations.AddField(
            model_name='dokumentstavke',
            name='dokument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtbook.dokumenti'),
        ),
        migrations.AddField(
            model_name='transakcije',
            name='dokument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtbook.dokumenti'),
        ),
        migrations.AddField(
            model_name='transakcije',
            name='klijent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtbook.klijenti'),
        ),
    ]
