# Generated by Django 5.0.1 on 2025-09-27 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0009_dokumentstavke_transakcije_dokumenti_faktura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenti',
            name='dok_datum',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='dokumenti',
            name='prm_datum',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='dokumentstavke',
            name='naziv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transakcije',
            name='tra_datum',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dokumentstavke',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dokumentstavke',
            name='jed_mere',
            field=models.CharField(choices=[('KT', 'komplet'), ('H87', 'kom'), ('HUR', 'h')], default='H87', max_length=3, verbose_name='Jedinica mere'),
        ),
        migrations.AlterField(
            model_name='dokumentstavke',
            name='tip_prometa',
            field=models.CharField(choices=[('U', 'usluga'), ('P', 'prodaja')], default='U', max_length=7),
        ),
    ]
