# Generated by Django 5.0.1 on 2025-09-28 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0010_dokumenti_dok_datum_dokumenti_prm_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenti',
            name='dok_tip',
            field=models.CharField(choices=[('IZF', 'Izlazna faktura'), ('ULF', 'Ulazna faktura'), ('OTP', 'Otpremnica'), ('RAC', 'Račun')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='klijent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtbook.klijenti'),
        ),
    ]
