# Generated by Django 5.0.1 on 2025-10-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0011_alter_dokumenti_dok_tip_alter_dokumenti_klijent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenti',
            name='dok_tip',
            field=models.CharField(choices=[('IZF', 'izlazna faktura'), ('ULF', 'ulazna faktura'), ('OTP', 'otpremnica'), ('RAC', 'faktura (van SEF-a)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='status_SEF',
            field=models.CharField(choices=[('NAC', 'Nacrt'), ('POS', 'Poslato'), ('OTK', 'Otkazana'), ('STO', 'Stornirano'), ('SLA', 'Slanje'), ('NOV', 'Nova'), ('PRI', 'Prihvaćeno'), ('ODB', 'Odbijeno'), ('GRE', 'Greška prilikom slanja'), ('PRE', 'Pregledano'), ('PON', 'Ponovo obavešteni'), ('NP', 'Nije primenljivo')], default='NAC', max_length=25),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='status_fak',
            field=models.CharField(choices=[('NEP', 'Neplaćen'), ('DEL', 'Delimično plaćen'), ('PLA', 'Plaćen')], default='NEP', max_length=25),
        ),
        migrations.AlterField(
            model_name='dokumentstavke',
            name='dokument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='gtbook.dokumenti'),
        ),
        migrations.AlterField(
            model_name='dokumentstavke',
            name='jed_mere',
            field=models.CharField(choices=[('KT', 'kompl.'), ('H87', 'kom.'), ('HUR', 'h')], default='H87', max_length=3, verbose_name='Jedinica mere'),
        ),
        migrations.AlterField(
            model_name='dokumentstavke',
            name='kolicina',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
