# Generated by Django 5.0.1 on 2025-10-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0012_alter_dokumenti_dok_tip_alter_dokumenti_status_sef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenti',
            name='dok_tip',
            field=models.CharField(choices=[('IZF', 'IZLAZNA FAKTURA'), ('ULF', 'ULAZNA FAKTURA'), ('OTP', 'OTPREMNICA')], max_length=3),
        ),
    ]
