# Generated by Django 5.0.1 on 2025-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0014_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='type',
            field=models.CharField(choices=[('ulazne', 'Ulazne'), ('izlazne', 'Izlazne')], default='izlazne', max_length=20),
        ),
    ]
