# Generated by Django 5.2.5 on 2025-11-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0015_webhookevent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakturaStavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.TextField(blank=True, null=True)),
                ('tip_prometa', models.CharField(choices=[('U', 'usluga'), ('P', 'prodaja')], default='U', max_length=7)),
                ('kolicina', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jed_mere', models.CharField(choices=[('KT', 'kompl.'), ('H87', 'kom.'), ('HUR', 'h')], default='H87', max_length=3)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke_izf', to='gtbook.dokumenti')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpremnicaStavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.TextField(blank=True, null=True)),
                ('tip_prometa', models.CharField(choices=[('U', 'usluga'), ('P', 'prodaja')], default='U', max_length=7)),
                ('kolicina', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jed_mere', models.CharField(choices=[('KT', 'kompl.'), ('H87', 'kom.'), ('HUR', 'h')], default='H87', max_length=3)),
                ('otpremnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke_otp', to='gtbook.dokumenti')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UlaznaFakturaStavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.TextField(blank=True, null=True)),
                ('tip_prometa', models.CharField(choices=[('U', 'usluga'), ('P', 'prodaja')], default='U', max_length=7)),
                ('kolicina', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jed_mere', models.CharField(choices=[('KT', 'kompl.'), ('H87', 'kom.'), ('HUR', 'h')], default='H87', max_length=3)),
                ('ulazna_faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke_ulf', to='gtbook.dokumenti')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
