# Generated by Django 5.2.5 on 2025-11-23 21:09

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0017_split_document_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakturastavka',
            name='iznos_stavke',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('kolicina'), '*', models.F('cena')), output_field=models.DecimalField(decimal_places=2, max_digits=12)),
        ),
        migrations.AddField(
            model_name='otpremnicastavka',
            name='iznos_stavke',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('kolicina'), '*', models.F('cena')), output_field=models.DecimalField(decimal_places=2, max_digits=12)),
        ),
        migrations.AddField(
            model_name='ulaznafakturastavka',
            name='iznos_stavke',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('kolicina'), '*', models.F('cena')), output_field=models.DecimalField(decimal_places=2, max_digits=12)),
        ),
        migrations.AlterField(
            model_name='fakturastavka',
            name='jed_mere',
            field=models.CharField(choices=[('KT', 'kompl.'), ('H87', 'kom.'), ('HUR', 'h')], default='H87', max_length=3, verbose_name='Jedinica mere'),
        ),
        migrations.AlterField(
            model_name='otpremnicastavka',
            name='jed_mere',
            field=models.CharField(choices=[('KT', 'kompl.'), ('H87', 'kom.'), ('HUR', 'h')], default='H87', max_length=3, verbose_name='Jedinica mere'),
        ),
        migrations.AlterField(
            model_name='ulaznafakturastavka',
            name='jed_mere',
            field=models.CharField(choices=[('KT', 'kompl.'), ('H87', 'kom.'), ('HUR', 'h')], default='H87', max_length=3, verbose_name='Jedinica mere'),
        ),
    ]
