# Generated by Django 5.0.1 on 2025-12-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0018_fakturastavka_iznos_stavke_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DokumentStavke',
        ),
    ]
