# Generated by Django 5.0.1 on 2025-12-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0019_delete_dokumentstavke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumenti',
            old_name='documentId',
            new_name='invoiceId',
        ),
    ]
