# Generated by Django 5.0.1 on 2025-12-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0020_rename_documentid_dokumenti_invoiceid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ['-received_at']},
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='status_SEF',
            field=models.CharField(choices=[('NAC', 'Nacrt'), ('POS', 'Poslato'), ('OTK', 'Otkazana'), ('STO', 'Stornirano'), ('SLA', 'Slanje'), ('NOV', 'Nova'), ('PRI', 'Prihvaćeno'), ('ODB', 'Odbijeno'), ('GRE', 'Greška prilikom slanja'), ('PRE', 'Pregledano'), ('PON', 'Ponovo obavešteni'), ('NEP', 'Nije primenljivo')], default='NAC', max_length=25),
        ),
    ]
