# Generated by Django 5.0.1 on 2025-12-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0021_alter_webhookevent_options_webhookevent_attempts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='next_retry_at',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='processed',
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
