# Generated by Django 5.2.5 on 2025-12-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0022_alter_webhookevent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookevent',
            name='error',
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
