# Generated by Django 5.2.5 on 2025-12-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0023_remove_webhookevent_error_webhookevent_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
