# Generated by Django 5.2.5 on 2025-12-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0025_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenti',
            name='efaktura',
            field=models.BooleanField(default=True),
        ),
    ]
