# Generated by Django 5.2.5 on 2025-12-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0026_dokumenti_efaktura'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenti',
            name='is_storno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokumenti',
            name='storno_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storno_docs', to='gtbook.dokumenti'),
        ),
    ]
