# Generated by Django 5.2.5 on 2025-12-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0027_dokumenti_is_storno_dokumenti_storno_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenti',
            name='status_fak',
            field=models.CharField(choices=[('NEP', 'Neplaćen'), ('DEL', 'Delimično plaćen'), ('PLA', 'Plaćen'), ('STO', 'Storno')], default='NEP', max_length=25),
        ),
    ]
