# Generated by Django 5.2.5 on 2025-12-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0028_alter_dokumenti_status_fak'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenti',
            name='comment_SEF',
            field=models.TextField(blank=True, null=True),
        ),
    ]
