# Generated by Django 5.2.5 on 2025-12-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0029_dokumenti_comment_sef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookevent',
            name='processed',
        ),
    ]
