# Generated by Django 5.2.5 on 2025-12-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtbook', '0030_remove_webhookevent_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenti',
            name='purchaseInvoiceId',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='salesInvoiceId',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
